#!/usr/bin/env bash
# Build the CFW C blob (src/) and emit:
#   OUT/wraps.h                   WRAP(return addr, original target, tag) for src/hooks.txt "wrap" sites
#   OUT/cfw.elf, OUT/cfw.map      linked image (see src/link.ld)
#   OUT/cfw_blob.patch            rknano_fw.py patch staging it inside mod40
#   OUT/cfw_hooks.patch           branch patches for src/hooks.txt
#   OUT/syms.inc                  .equ for every global blob symbol, for patches/*.S
# Usage: tools/build_blob.sh OUTDIR STOCK_IMG
set -euo pipefail
out=$1 fw=$2
mkdir -p "$out/obj"

python3 tools/hooks.py wraps src/hooks.txt "$fw" > "$out/wraps.h"

CFLAGS=(-mthumb -mcpu=cortex-m3 -Os -std=gnu11 -ffreestanding -fno-builtin-printf
        -fno-common -fno-strict-aliasing
        -Wall -Wextra -Werror -Wno-unused-parameter -Isrc -I"$out")
objs=()
for s in src/*.c src/*.S; do
  o="$out/obj/$(basename "${s%.*}").o"
  arm-none-eabi-gcc "${CFLAGS[@]}" -c "$s" -o "$o"
  objs+=("$o")
done
arm-none-eabi-gcc -mthumb -mcpu=cortex-m3 -nostdlib -T src/link.ld \
  -Wl,-Map="$out/cfw.map" -o "$out/cfw.elf" "${objs[@]}" -lgcc -Wl,--no-warn-rwx-segments
arm-none-eabi-objcopy -O binary "$out/cfw.elf" "$out/cfw.bin"
arm-none-eabi-nm -g "$out/cfw.elf" > "$out/cfw.nm"

python3 tools/hooks.py patches src/hooks.txt "$fw" "$out/cfw.nm" > "$out/cfw_hooks.patch"

python3 - "$out" <<'EOF'
import sys
out = sys.argv[1]
syms = {n: int(v, 16) for v, t, n in (l.split() for l in open(f"{out}/cfw.nm")) if t in "TtDdBbA"}
with open(f"{out}/syms.inc", "w") as f:
    f.write("@ generated by tools/build_blob.sh - CFW blob symbols\n")
    for n in sorted(syms):
        f.write("    .equ %-24s 0x%08x\n" % (n + ",", syms[n]))
data = open(f"{out}/cfw.bin", "rb").read()
with open(f"{out}/cfw_blob.patch", "w") as f:
    f.write("# generated by tools/build_blob.sh - CFW blob staged in mod40\n")
    f.write("40:%08x:%s\n" % (syms["cfw_stub"], data.hex()))
end = syms["__bss_end"]
print("cfw blob: %d bytes staged at 0x%08x, RAM 0x%08x..0x%08x (%d bytes free)" % (
    len(data), syms["cfw_stub"], syms["__blob_start"], end, 0x0309fff0 - end))
EOF
