#!/usr/bin/env python3
"""Turn src/hooks.txt into branch patches and a C table of wrapped call sites.

  hooks.py wraps   HOOKS STOCK_IMG          -> wraps.h on stdout
  hooks.py patches HOOKS STOCK_IMG NMFILE   -> rknano_fw.py patch lines on stdout
"""
import sys

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from rknano_fw import load  # noqa: E402


def parse(path):
    for n, line in enumerate(open(path), 1):
        f = line.split("#")[0].split()
        if not f:
            continue
        if f[2] not in ("bl", "b", "wrap") or len(f) < 4:
            sys.exit("%s:%d: bad hook line" % (path, n))
        yield dict(mod=int(f[0]), addr=int(f[1], 16), op=f[2], sym=f[3],
                   tag=f[4] if len(f) > 4 else "", line=n)


def decode_t32_branch(hw1, hw2, pc):
    """Target of a Thumb-2 bl / b.w (T4) at pc, or None."""
    if hw1 >> 11 != 0x1e or not hw2 & 0x8000 or not hw2 & 0x1000:
        return None
    s = (hw1 >> 10) & 1
    i1 = ~((hw2 >> 13) & 1 ^ s) & 1
    i2 = ~((hw2 >> 11) & 1 ^ s) & 1
    off = s << 24 | i1 << 23 | i2 << 22 | (hw1 & 0x3ff) << 12 | (hw2 & 0x7ff) << 1
    if s:
        off -= 1 << 25
    return pc + 4 + off


def encode_t32_branch(pc, target, link):
    off = target - (pc + 4)
    if off & 1 or not -(1 << 24) <= off < 1 << 24:
        raise ValueError("branch 0x%08x -> 0x%08x out of range" % (pc, target))
    s = (off >> 24) & 1
    j1 = ~((off >> 23) & 1 ^ s) & 1
    j2 = ~((off >> 22) & 1 ^ s) & 1
    hw1 = 0xf000 | s << 10 | (off >> 12) & 0x3ff
    hw2 = (0xd000 if link else 0x9000) | j1 << 13 | j2 << 11 | (off >> 1) & 0x7ff
    return hw1.to_bytes(2, "little") + hw2.to_bytes(2, "little")


def original_target(im, h):
    off, _ = im.region(h["mod"], h["addr"])
    hw1 = int.from_bytes(im.d[off:off + 2], "little")
    hw2 = int.from_bytes(im.d[off + 2:off + 4], "little")
    t = decode_t32_branch(hw1, hw2, h["addr"])
    if t is None or not hw2 >> 14 & 1:
        sys.exit("hooks.txt:%d: 0x%08x is not a bl" % (h["line"], h["addr"]))
    return t


def main():
    cmd, hooks, img = sys.argv[1:4]
    im = load(img)
    hs = list(parse(hooks))
    if cmd == "wraps":
        print("/* generated by tools/hooks.py from %s */" % hooks)
        for h in hs:
            if h["op"] == "wrap":
                print('WRAP(0x%08x, 0x%08x, "%s")' % (h["addr"] + 4, original_target(im, h), h["tag"]))
    elif cmd == "patches":
        syms = {}
        for line in open(sys.argv[4]):
            f = line.split()
            if len(f) == 3:
                syms[f[2]] = int(f[0], 16)
        print("# generated by tools/hooks.py from %s" % hooks)
        for h in hs:
            if h["sym"] not in syms:
                sys.exit("hooks.txt:%d: unknown symbol %s" % (h["line"], h["sym"]))
            if h["op"] == "wrap":
                original_target(im, h)
            code = encode_t32_branch(h["addr"], syms[h["sym"]], h["op"] != "b")
            print("%d:%08x:%s   # %s %s %s" % (h["mod"], h["addr"], code.hex(), h["op"], h["sym"], h["tag"]))
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
